### ISSUE TITLE
.s doesn't list tasks in inbox

### ISSUE THREAD

**Issue by jzk** [rhydlewis/search-omnifocus#10]
Hi, I am not sure if this is intentional. but from the statement "Search for all tasks within OmniFocus (irrespective of status) with .s:", I assume it will search task in inbox too, which is not the case on my side. ".i" works perfectly though. If it is intentional behavior, can you define another keyword for "truely search for all tasks"?

**Comment by rhydlewis** [comment]
Hi, it is intentional. From my point of view, the Inbox is where I store my unprocessed 'stuff'. When I want to search Omnifocus then, typically, I will be looking for stuff I have processed. I rarely search the Inbox because I have yet to work through it.

I'll look at adding in a true 'search-all' keyword (something like *.a*) for a future release.

**Comment by jzk** [comment]
thanks.
