### ISSUE TITLE
Add a task

### ISSUE THREAD

**Issue by wassimseif** [rhydlewis/search-omnifocus#22]
Is there anyway to add a task to omnifocus through this workflow ?
other side question, how can i list all my tasks ?
Thanks for this awesome workflow

**Comment by rhydlewis** [comment]
Thanks for the feedback - much appreciated. To answer your questions:

* _Can I add tasks?_ No, not really. This workflow helps you search your data. I keep anything that updates OmniFocus in separate workflows. I use [this simple workflow 'Create new OmniFocus task v1.0.0.zip'](https://github.com/rhydlewis/search-omnifocus/files/713273/Create.new.OmniFocus.task.v1.0.0.zip) to add new tasks to the Inbox via Alfred.
* _How do I list all tasks?_ This isn't really a scenario I've thought of doing (mostly because paging through 10's of tasks at a time through Alfred isn't something I need to do). You could try using `.se  ` which uses a space (' ') as the search parameter to show you _nearly_ everything (it won't find any 1 word tasks though...)

Hope this helps.
